services:
  nextlean:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3000:3000"
    volumes:
      - ./lean_project:/home/node/app/lean_project
      - ./data:/home/node/app/.data
    env_file:
      - .env
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - ELAN_HOME=/home/node/.elan
      - PATH=/home/node/.elan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
